// IT IS GENERATED BY FLR - DO NOT MODIFY BY HAND
// YOU CAN GET MORE DETAILS ABOUT FLR FROM:
// - https://github.com/Fly-Mix/flr-cli
// - https://github.com/Fly-Mix/flr-vscode-extension
// - https://github.com/Fly-Mix/flr-as-plugin
//

// ignore: unused_import
import 'package:flutter/widgets.dart';
// ignore: unused_import
import 'package:flutter/services.dart' show rootBundle;
// ignore: unused_import
import 'package:path/path.dart' as path;
// ignore: unused_import
import 'package:flutter_svg/flutter_svg.dart';
// ignore: unused_import
import 'package:r_dart_library/asset_svg.dart';

/// This `R` class is generated and contains references to static asset resources.
class R {
  /// package name: flutter_r_demo
  static const package = "flutter_r_demo";

  /// This `R.image` struct is generated, and contains static references to static non-svg type image asset resources.
  static const image = _R_Image();

  /// This `R.svg` struct is generated, and contains static references to static svg type image asset resources.
  static const svg = _R_Svg();

  /// This `R.text` struct is generated, and contains static references to static text asset resources.
  static const text = _R_Text();

  /// This `R.fontFamily` struct is generated, and contains static references to static font asset resources.
  static const fontFamily = _R_FontFamily();
}

/// Asset resource’s metadata class.
/// For example, here is the metadata of `packages/flutter_demo/assets/images/example.png` asset:
/// - packageName：flutter_demo
/// - assetName：assets/images/example.png
/// - fileDirname：assets/images
/// - fileBasename：example.png
/// - fileBasenameNoExtension：example
/// - fileExtname：.png
class AssetResource {
  /// Creates an object to hold the asset resource’s metadata.
  const AssetResource(this.assetName, {this.packageName});

  /// The name of the main asset from the set of asset resources to choose from.
  final String assetName;

  /// The name of the package from which the asset resource is included.
  final String? packageName;

  /// The name used to generate the key to obtain the asset resource. For local assets
  /// this is [assetName], and for assets from packages the [assetName] is
  /// prefixed 'packages/<package_name>/'.
  String get keyName =>
      packageName == null ? assetName : "packages/$packageName/$assetName";

  /// The file basename of the asset resource.
  String get fileBasename {
    final basename = path.basename(assetName);
    return basename;
  }

  /// The no extension file basename of the asset resource.
  String get fileBasenameNoExtension {
    final basenameWithoutExtension = path.basenameWithoutExtension(assetName);
    return basenameWithoutExtension;
  }

  /// The file extension name of the asset resource.
  String get fileExtname {
    final extension = path.extension(assetName);
    return extension;
  }

  /// The directory path name of the asset resource.
  String get fileDirname {
    var dirname = assetName;
    if (packageName != null) {
      final packageStr = "packages/$packageName/";
      dirname = dirname.replaceAll(packageStr, "");
    }
    final filenameStr = "$fileBasename/";
    dirname = dirname.replaceAll(filenameStr, "");
    return dirname;
  }
}

// ignore: camel_case_types
class _R_Image_AssetResource {
  const _R_Image_AssetResource();

  /// asset: lib/flr.assets/images/test_gif/test_gif.gif
  // ignore: non_constant_identifier_names
  final test_gif = const AssetResource(
    "flr.assets/images/test_gif/test_gif.gif",
    packageName: R.package,
  );

  /// asset: lib/flr.assets/images/test_jpg_variant/test_jpg_variant.jpg
  // ignore: non_constant_identifier_names
  final test_jpg_variant = const AssetResource(
    "flr.assets/images/test_jpg_variant/test_jpg_variant.jpg",
    packageName: R.package,
  );

  /// asset: lib/flr.assets/images/test_no_main_asset/test_no_main_asset.png
  // ignore: non_constant_identifier_names
  final test_no_main_asset = const AssetResource(
    "flr.assets/images/test_no_main_asset/test_no_main_asset.png",
    packageName: R.package,
  );

  /// asset: lib/flr.assets/images/test_only_1.5x_variant/test_only_1.5x_variant.png
  // ignore: non_constant_identifier_names
  final test_only_1_5x_variant = const AssetResource(
    "flr.assets/images/test_only_1.5x_variant/test_only_1.5x_variant.png",
    packageName: R.package,
  );

  /// asset: lib/flr.assets/images/test_only_main_asset_0/test_only_main_asset_0.png
  // ignore: non_constant_identifier_names
  final test_only_main_asset_0 = const AssetResource(
    "flr.assets/images/test_only_main_asset_0/test_only_main_asset_0.png",
    packageName: R.package,
  );

  /// asset: lib/flr.assets/images/test_png_variant_0/test_png_variant_0.png
  // ignore: non_constant_identifier_names
  final test_png_variant_0 = const AssetResource(
    "flr.assets/images/test_png_variant_0/test_png_variant_0.png",
    packageName: R.package,
  );
}

// ignore: camel_case_types
class _R_Svg_AssetResource {
  const _R_Svg_AssetResource();

  /// asset: lib/flr.assets/images/test_3.0x_svg/test_3.0x_svg.svg
  // ignore: non_constant_identifier_names
  final test_3_0x_svg = const AssetResource(
    "flr.assets/images/test_3.0x_svg/test_3.0x_svg.svg",
    packageName: R.package,
  );

  /// asset: lib/flr.assets/images/test_svg/test_svg.svg
  // ignore: non_constant_identifier_names
  final test_svg = const AssetResource(
    "flr.assets/images/test_svg/test_svg.svg",
    packageName: R.package,
  );
}

// ignore: camel_case_types
class _R_Text_AssetResource {
  const _R_Text_AssetResource();

  /// asset: lib/flr.assets/rawfiles/test_json/test_json.json
  // ignore: non_constant_identifier_names
  final test_json = const AssetResource(
    "flr.assets/rawfiles/test_json/test_json.json",
    packageName: R.package,
  );

  /// asset: lib/flr.assets/rawfiles/test_txt/test_txt.txt
  // ignore: non_constant_identifier_names
  final test_txt = const AssetResource(
    "flr.assets/rawfiles/test_txt/test_txt.txt",
    packageName: R.package,
  );

  /// asset: lib/flr.assets/rawfiles/test_yaml/test_yaml.yaml
  // ignore: non_constant_identifier_names
  final test_yaml = const AssetResource(
    "flr.assets/rawfiles/test_yaml/test_yaml.yaml",
    packageName: R.package,
  );
}

/// This `_R_Image` class is generated and contains references to static non-svg type image asset resources.
// ignore: camel_case_types
class _R_Image {
  const _R_Image();

  final asset = const _R_Image_AssetResource();

  /// asset: lib/flr.assets/images/test_gif/test_gif.gif
  // ignore: non_constant_identifier_names
  AssetImage test_gif() {
    return AssetImage(asset.test_gif.keyName);
  }

  /// asset: lib/flr.assets/images/test_jpg_variant/test_jpg_variant.jpg
  // ignore: non_constant_identifier_names
  AssetImage test_jpg_variant() {
    return AssetImage(asset.test_jpg_variant.keyName);
  }

  /// asset: lib/flr.assets/images/test_no_main_asset/test_no_main_asset.png
  // ignore: non_constant_identifier_names
  AssetImage test_no_main_asset() {
    return AssetImage(asset.test_no_main_asset.keyName);
  }

  /// asset: lib/flr.assets/images/test_only_1.5x_variant/test_only_1.5x_variant.png
  // ignore: non_constant_identifier_names
  AssetImage test_only_1_5x_variant() {
    return AssetImage(asset.test_only_1_5x_variant.keyName);
  }

  /// asset: lib/flr.assets/images/test_only_main_asset_0/test_only_main_asset_0.png
  // ignore: non_constant_identifier_names
  AssetImage test_only_main_asset_0() {
    return AssetImage(asset.test_only_main_asset_0.keyName);
  }

  /// asset: lib/flr.assets/images/test_png_variant_0/test_png_variant_0.png
  // ignore: non_constant_identifier_names
  AssetImage test_png_variant_0() {
    return AssetImage(asset.test_png_variant_0.keyName);
  }
}

/// This `_R_Svg` class is generated and contains references to static svg type image asset resources.
// ignore: camel_case_types
class _R_Svg {
  const _R_Svg();

  final asset = const _R_Svg_AssetResource();

  /// asset: lib/flr.assets/images/test_3.0x_svg/test_3.0x_svg.svg
  // ignore: non_constant_identifier_names
  AssetSvg test_3_0x_svg({required double width, required double height}) {
    final imageProvider = AssetSvg(
      asset.test_3_0x_svg.keyName,
      width: width,
      height: height,
    );
    return imageProvider;
  }

  /// asset: lib/flr.assets/images/test_svg/test_svg.svg
  // ignore: non_constant_identifier_names
  AssetSvg test_svg({required double width, required double height}) {
    final imageProvider = AssetSvg(
      asset.test_svg.keyName,
      width: width,
      height: height,
    );
    return imageProvider;
  }
}

/// This `_R_Text` class is generated and contains references to static text asset resources.
// ignore: camel_case_types
class _R_Text {
  const _R_Text();

  final asset = const _R_Text_AssetResource();

  /// asset: lib/flr.assets/rawfiles/test_json/test_json.json
  // ignore: non_constant_identifier_names
  Future<String> test_json() {
    final str = rootBundle.loadString(asset.test_json.keyName);
    return str;
  }

  /// asset: lib/flr.assets/rawfiles/test_txt/test_txt.txt
  // ignore: non_constant_identifier_names
  Future<String> test_txt() {
    final str = rootBundle.loadString(asset.test_txt.keyName);
    return str;
  }

  /// asset: lib/flr.assets/rawfiles/test_yaml/test_yaml.yaml
  // ignore: non_constant_identifier_names
  Future<String> test_yaml() {
    final str = rootBundle.loadString(asset.test_yaml.keyName);
    return str;
  }
}

/// This `_R_FontFamily` class is generated and contains references to static font asset resources.
// ignore: camel_case_types
class _R_FontFamily {
  const _R_FontFamily();

  /// font family: Amiri
  // ignore: non_constant_identifier_names
  final amiri = "Amiri";

  /// font family: Baloo_Thambi_2
  // ignore: non_constant_identifier_names
  final baloo_Thambi_2 = "Baloo_Thambi_2";

  /// font family: Dan_Zhai_Hang_Shu_Cai
  // ignore: non_constant_identifier_names
  final dan_Zhai_Hang_Shu_Cai = "Dan_Zhai_Hang_Shu_Cai";

  /// font family: Liu_Jian_Mao_Cao
  // ignore: non_constant_identifier_names
  final liu_Jian_Mao_Cao = "Liu_Jian_Mao_Cao";

  /// font family: Sky_IconFont
  // ignore: non_constant_identifier_names
  final sky_IconFont = "Sky_IconFont";

  /// font family: YorkFish_IconFont
  // ignore: non_constant_identifier_names
  final yorkFish_IconFont = "YorkFish_IconFont";
}
